name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright Browsers
        run: python3 -m playwright install

      - name: Run Playwright Tests
        env:
          PWDEBUG: 1
        run: python3 -m pytest -m basic_search
