name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies and test start
        run: |
          python3 -m venv venv
          . venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m playwright install
          python -m pytest -m basic_search
